const USER_FETCH_REQUEST = 'USER_FETC_REQUEST'
const USER_FETCH_SUCCESS = 'USER_FETC_SUCCESS'
const USER_FETCH_FAILURE = 'USER_FETC_FAILURE'


export {USER_FETCH_REQUEST,USER_FETCH_SUCCESS,USER_FETCH_FAILURE}